/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ifndb;

import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JLabel;

/**
 *
 * @author Reale
 */
public class FrameOrdiniperCliente extends javax.swing.JFrame {

    /**
     * Creates new form FrameOrdiniperCliente
     */

    // Conversione arraylist a string

    public FrameOrdiniperCliente() {
        initComponents();

        try {
            IFNDB.recoverFilterOrders(FilterCombo);
            IFNDB.recoverClientiCombo(IdClienteCombo);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

    }
    // fine conversione

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IdClienteCombo = new javax.swing.JComboBox<>();
        FilterCombo = new javax.swing.JComboBox<>();
        BTNVisualizza = new javax.swing.JButton();
        BTNElimina = new javax.swing.JButton();
        IdclienteLB1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        ClienteCheck = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ricerca per cliente");
        setPreferredSize(new java.awt.Dimension(958, 691));

        IdClienteCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        IdClienteCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IdClienteComboMouseClicked(evt);
            }
        });
        IdClienteCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdClienteComboActionPerformed(evt);
            }
        });

        FilterCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ascendente", "Discendente" }));
        FilterCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilterComboActionPerformed(evt);
            }
        });

        BTNVisualizza.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        BTNVisualizza.setText("Visualizza");
        BTNVisualizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNVisualizzaActionPerformed(evt);
            }
        });

        BTNElimina.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        BTNElimina.setForeground(new java.awt.Color(204, 0, 0));
        BTNElimina.setText("Elimina");

        IdclienteLB1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        IdclienteLB1.setText("Ordina per:");

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "OrderID", "CustomerID", "EmployeeID", "OrderDate"
            }
        ));
        jScrollPane1.setViewportView(table);

        ClienteCheck.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        ClienteCheck.setText("Filtra Cliente:");
        ClienteCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteCheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(IdclienteLB1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(FilterCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(IdClienteCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(ClienteCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 9, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(544, 544, 544)
                        .addComponent(BTNElimina)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BTNVisualizza))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNElimina)
                    .addComponent(BTNVisualizza))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(IdclienteLB1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FilterCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ClienteCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IdClienteCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNOrdinaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BTNOrdinaActionPerformed
        // TODO add your handling code here:
        try {
            String t = (String) IdClienteCombo.getSelectedItem();
            IFNDB.recoverFilterOrders(FilterCombo);
            // IFNDB.visualizzaCliente(st, FAsc, table);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }// GEN-LAST:event_BTNOrdinaActionPerformed

    private void IdClienteComboActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_IdClienteComboActionPerformed
        // TODO add your handling code here:

    }// GEN-LAST:event_IdClienteComboActionPerformed

    private void BTNVisualizzaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BTNVisualizzaActionPerformed
        // TODO add your handling code here:

        try {
            String t = (String) FilterCombo.getSelectedItem();
            System.out.println("FAsc value:" + t);
            IFNDB.visualizzaCliente((String) IdClienteCombo.getSelectedItem(), t, table, ClienteCheck.isSelected());
            System.out.println(ClienteCheck.isSelected());
            System.out.println("FAsc value:" + t);

        } catch (ClassNotFoundException | SQLException e) {
            System.out.println(e.getMessage());
        }

    }// GEN-LAST:event_BTNVisualizzaActionPerformed

    private void FilterComboActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_FilterComboActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_FilterComboActionPerformed

    private void IdClienteComboMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_IdClienteComboMouseClicked
        // TODO add your handling code here:

    }// GEN-LAST:event_IdClienteComboMouseClicked

    private void ClienteCheckActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ClienteCheckActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_ClienteCheckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameOrdiniperCliente.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameOrdiniperCliente.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameOrdiniperCliente.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameOrdiniperCliente.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new FrameOrdiniperCliente().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNElimina;
    private javax.swing.JButton BTNVisualizza;
    private javax.swing.JCheckBox ClienteCheck;
    private javax.swing.JComboBox<String> FilterCombo;
    private javax.swing.JComboBox<String> IdClienteCombo;
    private javax.swing.JLabel IdclienteLB1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
